class Autogenerated {
  Null message;
  late List<Results> results;
  late int status;

  Autogenerated({this.message, required this.results, required this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    if (json['results'] != null) {
      results = <Results>[];
      json['results'].forEach((v) {
        results.add(new Results.fromJson(v));
      });
    }
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['results'] = this.results.map((v) => v.toJson()).toList();
    data['status'] = this.status;
    return data;
  }
}

class Results {
  String? address1;
  String? address2;
  String? address3;
  String? kana1;
  String? kana2;
  String? kana3;
  String? prefcode;
  String? zipcode;

  Results(
      {required this.address1,
      required this.address2,
      required this.address3,
      required this.kana1,
      required this.kana2,
      required this.kana3,
      required this.prefcode,
      required this.zipcode});

  Results.fromJson(Map<String, dynamic> json) {
    address1 = json['address1'];
    address2 = json['address2'];
    address3 = json['address3'];
    kana1 = json['kana1'];
    kana2 = json['kana2'];
    kana3 = json['kana3'];
    prefcode = json['prefcode'];
    zipcode = json['zipcode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['address1'] = this.address1;
    data['address2'] = this.address2;
    data['address3'] = this.address3;
    data['kana1'] = this.kana1;
    data['kana2'] = this.kana2;
    data['kana3'] = this.kana3;
    data['prefcode'] = this.prefcode;
    data['zipcode'] = this.zipcode;
    return data;
  }
}
